services:

  zookeeper-finance:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-finance
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-finance:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-finance
    depends_on:
      - zookeeper-finance
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-finance:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui-finance:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-finance
    depends_on:
      - kafka-finance
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: finance
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-finance:9093

  minio-finance:
    image: minio/minio:latest
    container_name: minio-finance
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres-airflow:
    image: postgres:15
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  airflow-finance:
    image: apache/airflow:2.9.0
    container_name: airflow-finance
    depends_on:
      postgres-airflow:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: finance_secret_key_2026
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs_airflow:/opt/airflow/logs
      - .:/opt/airflow/project
    command: >
      bash -c "pip install pandas duckdb boto3 apscheduler yfinance requests websocket-client kafka-python && airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname Finance --role Admin --email admin@finance.com && airflow webserver & airflow scheduler"

volumes:
  minio_data:
  postgres_airflow_data: